const API_URL = "http://127.0.0.1:8000";

// DOM Elements
const rulesTableBody = document.querySelector('#rules-table tbody');
const logsContainer = document.querySelector('#logs-container');
const simulateBtn = document.getElementById('simulate-btn');
const simulationResult = document.getElementById('simulation-result');
const refreshLogsBtn = document.getElementById('refresh-logs');

// Modal Elements
const ruleModal = document.getElementById('rule-modal');
const addRuleBtn = document.getElementById('add-rule-modal-btn');
const closeModalBtn = document.querySelector('.close-modal');
const saveRuleBtn = document.getElementById('save-rule-btn');
const cancelRuleBtn = document.getElementById('cancel-rule-btn');
// --- Initialization ---
document.addEventListener('DOMContentLoaded', () => {
    // Select elements inside DOMContentLoaded to ensure they exist
    const ruleModal = document.getElementById('rule-modal');
    const addRuleBtn = document.getElementById('add-rule-modal-btn');
    const closeModalBtn = document.querySelector('.close-modal');
    const saveRuleBtn = document.getElementById('save-rule-btn');
    const cancelRuleBtn = document.getElementById('cancel-rule-btn');

    // Other elements
    const simulateBtn = document.getElementById('simulate-btn');
    const refreshLogsBtn = document.getElementById('refresh-logs');

    // Load initial data
    fetchRules();
    fetchLogs();

    // Auto-refresh logs every 5 seconds
    setInterval(fetchLogs, 5000);

    // --- Event Listeners ---

    // Open Modal
    if (addRuleBtn) {
        addRuleBtn.addEventListener('click', () => {
            ruleModal.classList.remove('hidden');
        });
    }

    // Close Modal (X button)
    if (closeModalBtn) {
        closeModalBtn.addEventListener('click', () => {
            console.log("Close modal clicked");
            ruleModal.classList.add('hidden');
        });
    }

    // Close Modal (Cancel button)
    if (cancelRuleBtn) {
        cancelRuleBtn.addEventListener('click', () => {
            ruleModal.classList.add('hidden');
        });
    }

    // Close Modal (Click outside)
    window.addEventListener('click', (e) => {
        if (e.target === ruleModal) {
            ruleModal.classList.add('hidden');
        }
    });

    // Save Rule
    if (saveRuleBtn) {
        saveRuleBtn.addEventListener('click', addRule);
    }

    // Simulation
    if (simulateBtn) {
        simulateBtn.addEventListener('click', simulatePacket);
    }

    // Refresh Logs
    if (refreshLogsBtn) {
        refreshLogsBtn.addEventListener('click', fetchLogs);
    }
});

// --- API Functions ---

async function fetchRules() {
    try {
        const response = await fetch(`${API_URL}/rules`);
        const rules = await response.json();
        renderRules(rules);
    } catch (error) {
        console.error("Error fetching rules:", error);
    }
}

async function addRule(event) {
    if (event) event.preventDefault();

    const action = document.getElementById('rule-action').value;
    const protocol = document.getElementById('rule-protocol').value;
    const sourceIpVal = document.getElementById('rule-source').value.trim();
    const destIpVal = document.getElementById('rule-dest').value.trim();
    const portVal = document.getElementById('rule-port').value.trim();

    // Defaults
    const sourceIp = sourceIpVal === "" ? "ANY" : sourceIpVal;
    const destIp = destIpVal === "" ? "ANY" : destIpVal;
    const port = portVal === "" ? 0 : parseInt(portVal);

    if (isNaN(port)) {
        alert("Port must be a valid number");
        return;
    }

    const rule = {
        // id: generated by server
        action,
        protocol,
        source_ip: sourceIp,
        destination_ip: destIp,
        port
    };

    console.log("Adding rule:", rule);

    try {
        const response = await fetch(`${API_URL}/rules`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(rule)
        });

        if (response.ok) {
            ruleModal.classList.add('hidden');
            fetchRules();
            // Reset form
            document.getElementById('rule-source').value = 'ANY';
            document.getElementById('rule-dest').value = 'ANY';
            document.getElementById('rule-port').value = '0';
        } else {
            const errText = await response.text();
            console.error("Failed to add rule:", errText);
            alert('Failed to add rule: ' + errText);
        }
    } catch (error) {
        console.error("Error adding rule:", error);
        alert("Error connecting to server. Is it running?");
    }
}

// Expose deleteRule to window for onclick attribute
window.deleteRule = async function (id) {
    if (!confirm('Are you sure you want to delete this rule?')) return;

    try {
        await fetch(`${API_URL}/rules/${id}`, { method: 'DELETE' });
        fetchRules();
    } catch (error) {
        console.error("Error deleting rule:", error);
    }
};

async function simulatePacket() {
    const protocol = document.querySelector('input[name="protocol"]:checked').value;
    const sourceIp = document.getElementById('source-ip').value;
    const destIp = document.getElementById('dest-ip').value;
    const port = parseInt(document.getElementById('port').value);

    // Basic Validation
    if (!sourceIp || !destIp) {
        alert("Please enter both Source and Destination IPs");
        return;
    }

    const packet = {
        protocol,
        source_ip: sourceIp,
        destination_ip: destIp,
        port
    };

    try {
        simulateBtn.textContent = "Simulating...";
        simulateBtn.disabled = true;

        const response = await fetch(`${API_URL}/simulate`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(packet)
        });

        const result = await response.json();

        displaySimulationResult(result);
        fetchLogs(); // Update logs immediately

    } catch (error) {
        console.error("Error simulating packet:", error);
    } finally {
        simulateBtn.textContent = "Send Packet";
        simulateBtn.disabled = false;
    }
}

async function fetchLogs() {
    try {
        const response = await fetch(`${API_URL}/logs`);
        const logs = await response.json();
        renderLogs(logs);
    } catch (error) {
        console.error("Error fetching logs:", error);
    }
}

// --- Render Functions ---

function renderRules(rules) {
    rulesTableBody.innerHTML = '';
    rules.forEach(rule => {
        const tr = document.createElement('tr');
        tr.innerHTML = `
            <td><span class="action-badge action-${rule.action}">${rule.action}</span></td>
            <td>${rule.protocol}</td>
            <td>${rule.source_ip}</td>
            <td>${rule.destination_ip}</td>
            <td>${rule.port === 0 ? 'Any' : rule.port}</td>
            <td>
                <button class="btn danger small" onclick="deleteRule('${rule.id}')">Delete</button>
            </td>
        `;
        rulesTableBody.appendChild(tr);
    });
}

function renderLogs(logs) {
    logsContainer.innerHTML = '';
    logs.forEach(log => {
        const div = document.createElement('div');
        div.className = 'log-entry';

        const time = new Date(log.timestamp * 1000).toLocaleTimeString();
        const actionClass = log.action === 'ALLOWED' ? 'action-ALLOWED' : 'action-BLOCKED';

        div.innerHTML = `
            <span class="log-time">[${time}]</span>
            <span class="log-info">
                ${log.packet.protocol} 
                ${log.packet.source_ip} &rarr; ${log.packet.destination_ip}:${log.packet.port}
            </span>
            <span class="log-action ${actionClass}">${log.action}</span>
        `;
        logsContainer.appendChild(div);
    });
}

function displaySimulationResult(log) {
    simulationResult.classList.remove('hidden');
    simulationResult.className = `result-box result-${log.action}`;

    if (log.action === "BLOCKED") {
        simulationResult.innerHTML = `🚫 PACKET BLOCKED (Rule: ${log.matched_rule_id ? log.matched_rule_id.substring(0, 8) + '...' : 'Default'})`;
    } else {
        simulationResult.innerHTML = `✅ PACKET ALLOWED`;
    }
}
